[2023-01-31T05:12:55.582+0000] {processor.py:153} INFO - Started process (PID=10065) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py
[2023-01-31T05:13:02.536+0000] {processor.py:743} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2023-01-31T05:13:19.897+0000] {logging_mixin.py:137} INFO - [2023-01-31T05:13:19.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py
[2023-01-31T05:14:26.746+0000] {logging_mixin.py:137} INFO - [2023-01-31T05:14:22.012+0000] {timeout.py:68} ERROR - Process timed out, PID: 10065
[2023-01-31T05:14:55.324+0000] {logging_mixin.py:137} INFO - [2023-01-31T05:14:31.767+0000] {dagbag.py:343} ERROR - Failed to import: /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py", line 25, in <module>
    from airflow.decorators import dag, task
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/__init__.py", line 21, in <module>
    from airflow.decorators.base import TaskDecorator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 278, in <module>
    class _TaskDecorator(ExpandableFactory, Generic[FParams, FReturn, OperatorSubclass]):
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_next_gen.py", line 146, in wrap
    return do_it(cls, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_next_gen.py", line 112, in do_it
    match_args=match_args,
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_make.py", line 1595, in attrs
    return wrap(maybe_cls)
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_make.py", line 1511, in wrap
    field_transformer,
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_make.py", line 664, in __init__
    field_transformer,
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_make.py", line 485, in _transform_attrs
    anns = _get_annotations(cls)
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_make.py", line 406, in _get_annotations
    if _has_own_attribute(cls, "__annotations__"):
  File "/home/airflow/.local/lib/python3.7/site-packages/attr/_make.py", line 395, in _has_own_attribute
    a = getattr(base_cls, attrib_name, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 10065
[2023-01-31T05:15:06.274+0000] {processor.py:755} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py
[2023-01-31T05:23:06.712+0000] {processor.py:175} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sla_dag.py took 622.945 seconds
