[2023-02-02T12:31:57.166+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2023-02-02T12:31:57.240+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2023-02-02T12:31:57.242+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:31:57.244+0000] {taskinstance.py:1280} INFO - Starting attempt 11 of 11
[2023-02-02T12:31:57.244+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T12:31:57.404+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2022-11-01 00:00:00+00:00
[2023-02-02T12:31:57.449+0000] {standard_task_runner.py:55} INFO - Started process 11177 to run task
[2023-02-02T12:31:57.493+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'task1', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '1188', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmphzco50ob']
[2023-02-02T12:31:57.511+0000] {standard_task_runner.py:83} INFO - Job 1188: Subtask task1
[2023-02-02T12:31:57.922+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.task1 scheduled__2022-11-01T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T12:31:58.213+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=11
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2023-02-02T12:31:58.219+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T12:31:58.228+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T12:31:58.287+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T12:31:58.313+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T12:31:58.323+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T12:31:58.353+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T12:31:58.373+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_catchup_backfill_v1, task_id=task1, execution_date=20221101T000000, start_date=20230202T123157, end_date=20230202T123158
[2023-02-02T12:31:58.436+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1188 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 11177)
[2023-02-02T12:31:58.525+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T12:31:58.597+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
