[2023-02-02T11:32:01.311+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.first_task scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2023-02-02T11:32:01.434+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.first_task scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2023-02-02T11:32:01.451+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:32:01.453+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-02T11:32:01.455+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:32:01.641+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): first_task> on 2022-11-08 00:00:00+00:00
[2023-02-02T11:32:01.686+0000] {standard_task_runner.py:55} INFO - Started process 9721 to run task
[2023-02-02T11:32:01.979+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'first_task', 'scheduled__2022-11-08T00:00:00+00:00', '--job-id', '1093', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmphrf_k5wh']
[2023-02-02T11:32:01.998+0000] {standard_task_runner.py:83} INFO - Job 1093: Subtask first_task
[2023-02-02T11:32:03.119+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.first_task scheduled__2022-11-08T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:32:05.533+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T00:00:00+00:00
[2023-02-02T11:32:05.786+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:32:05.825+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:32:07.733+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:32:08.197+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:32:08.521+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:32:10.872+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:32:11.729+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=first_task, execution_date=20221108T000000, start_date=20230202T113201, end_date=20230202T113211
[2023-02-02T11:32:13.268+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1093 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 9721)
[2023-02-02T11:32:13.765+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:32:14.193+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
