[2023-02-02T11:32:00.886+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.first_task scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-02T11:32:00.949+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v1.first_task scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2023-02-02T11:32:00.963+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:32:00.966+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-02T11:32:00.967+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T11:32:01.082+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): first_task> on 2022-11-12 00:00:00+00:00
[2023-02-02T11:32:01.215+0000] {standard_task_runner.py:55} INFO - Started process 9715 to run task
[2023-02-02T11:32:01.246+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v1', 'first_task', 'scheduled__2022-11-12T00:00:00+00:00', '--job-id', '1086', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpvt76vxpm']
[2023-02-02T11:32:01.247+0000] {standard_task_runner.py:83} INFO - Job 1086: Subtask first_task
[2023-02-02T11:32:02.302+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_catchup_backfill_v1.first_task scheduled__2022-11-12T00:00:00+00:00 [running]> on host 178c757a8fee
[2023-02-02T11:32:03.853+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=archana
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v1
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-12T00:00:00+00:00
[2023-02-02T11:32:03.883+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-02T11:32:03.909+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'This is a simple Bash Command!']
[2023-02-02T11:32:04.443+0000] {subprocess.py:86} INFO - Output:
[2023-02-02T11:32:04.738+0000] {subprocess.py:93} INFO - /bin/bash: line 1: This: command not found
[2023-02-02T11:32:04.807+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-02T11:32:05.417+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-02T11:32:05.629+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v1, task_id=first_task, execution_date=20221112T000000, start_date=20230202T113200, end_date=20230202T113205
[2023-02-02T11:32:09.648+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1086 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 9715)
[2023-02-02T11:32:12.376+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-02T11:32:13.322+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
